// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "ms-sale-transaction/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// SaleRepository is an autogenerated mock type for the SaleRepository type
type SaleRepository struct {
	mock.Mock
}

// FindAllSalesByMonth provides a mock function with given fields: val
func (_m *SaleRepository) FindAllSalesByMonth(val string) (*models.Sales, error) {
	ret := _m.Called(val)

	var r0 *models.Sales
	if rf, ok := ret.Get(0).(func(string) *models.Sales); ok {
		r0 = rf(val)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Sales)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(val)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindLatestSales provides a mock function with given fields: quantity
func (_m *SaleRepository) FindLatestSales(quantity int) (*models.Sales, error) {
	ret := _m.Called(quantity)

	var r0 *models.Sales
	if rf, ok := ret.Get(0).(func(int) *models.Sales); ok {
		r0 = rf(quantity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Sales)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
