// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "ms-sale-transaction/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// SalesService is an autogenerated mock type for the SalesService type
type SalesService struct {
	mock.Mock
}

// GetLatestSales provides a mock function with given fields: _a0
func (_m *SalesService) GetLatestSales(_a0 int) []*models.Sale {
	ret := _m.Called(_a0)

	var r0 []*models.Sale
	if rf, ok := ret.Get(0).(func(int) []*models.Sale); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Sale)
		}
	}

	return r0
}

// GetSales provides a mock function with given fields: _a0
func (_m *SalesService) GetSales(_a0 string) []*models.Sale {
	ret := _m.Called(_a0)

	var r0 []*models.Sale
	if rf, ok := ret.Get(0).(func(string) []*models.Sale); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Sale)
		}
	}

	return r0
}

// GetSalesByProduct provides a mock function with given fields: _a0
func (_m *SalesService) GetSalesByProduct(_a0 string) []*models.Sale {
	ret := _m.Called(_a0)

	var r0 []*models.Sale
	if rf, ok := ret.Get(0).(func(string) []*models.Sale); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Sale)
		}
	}

	return r0
}
